version: '3'

services:
  surrealdb:
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - admin
      - --pass
      - pass
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
